<?php
// This file generated by Propel 1.7.3-dev convert-conf target
// from XML runtime conf file /var/www/gc/p/cryptobboy/.admin/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'cryptobboy' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=gc_cryptobboy;charset=utf8;',
        'user' => 'gc_cryptobboy',
        'password' => 'iojinsbtifuyfjlgascclwgbizkqpkd',
      ),
    ),
    'default' => 'cryptobboy',
  ),
  'generator_version' => '1.7.3-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap.php');
return $conf;