<?php

namespace App;


$omMap = [
    [
        'name' => 'Asset',
        'desc' => 'Assets',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => [
            'trade',
            'asset_exchange',
        ],
        'display' => 'Asset',
    ],
    [
        'name' => 'AssetExchange',
        'desc' => 'Wallets',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Wallet',
    ],
    [
        'name' => 'Trade',
        'desc' => 'Trades',
        'parent_table' => 'asset',
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Asset - Trade',
    ],
    [
        'name' => 'Import',
        'desc' => 'Imports',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Import',
    ],
    [
        'name' => 'AuthyGroupX',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'TemplateFile',
        'desc' => 'Files',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'File',
    ],
    [
        'name' => 'MessageI18n',
        'desc' => '',
        'parent_table' => null,
        'parent_menu' => '',
        'child_table' => null,
        'display' => 'MessageI18n',
    ],
    [
        'name' => 'Authy',
        'desc' => 'Users',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'authy_group_x',
            'authy_log',
        ],
        'display' => 'User',
    ],
    [
        'name' => 'Country',
        'desc' => 'Countries',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Country',
    ],
    [
        'name' => 'Exchange',
        'desc' => 'Exchanges',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Exchange',
    ],
    [
        'name' => 'Token',
        'desc' => 'Tokens',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Token',
    ],
    [
        'name' => 'Symbol',
        'desc' => 'Symbols',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Symbol',
    ],
    [
        'name' => 'AuthyGroup',
        'desc' => 'Groups',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Group',
    ],
    [
        'name' => 'AuthyLog',
        'desc' => 'Login logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Login log',
    ],
    [
        'name' => 'Message',
        'desc' => 'Messages',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Message',
    ],
    [
        'name' => 'Config',
        'desc' => 'Settings',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'Setting',
    ],
    [
        'name' => 'ApiRbac',
        'desc' => 'API ACLs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'api_log',
        ],
        'display' => 'API ACL',
    ],
    [
        'name' => 'ApiLog',
        'desc' => 'API logs',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => null,
        'display' => 'API log',
    ],
    [
        'name' => 'Template',
        'desc' => 'Templates',
        'parent_table' => null,
        'parent_menu' => 'Settings',
        'child_table' => [
            'template_file',
        ],
        'display' => 'Template',
    ],
];
