<?php

namespace App;


    return [
    'html' => [
        'GET' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'POST' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
    ],
    'json' => [
        'GET' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'POST' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'PATCH' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
        'DELETE' => [
            'Authy' => [],
            'Country' => [],
            'Asset' => [],
            'AssetExchange' => [],
            'Trade' => [],
            'Exchange' => [],
            'Token' => [],
            'Symbol' => [],
            'Import' => [],
            'AuthyGroup' => [],
            'AuthyGroupX' => [],
            'AuthyLog' => [],
            'Message' => [],
            'Config' => [],
            'ApiRbac' => [],
            'ApiLog' => [],
            'Template' => [],
            'TemplateFile' => [],
        ],
    ],
];


